"""Initial

Revision ID: 23513ab5eda3
Revises: 
Create Date: 2023-06-22 22:19:56.136197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23513ab5eda3'
down_revision = None
branch_labels = None
depends_on = None

types = sa.Enum('folder', 'file', name='type')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', types, nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__relations'))
    )
    op.create_table('file_system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parentId', sa.Integer(), nullable=True),
    sa.Column('type', types, nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['parentId'], ['relations.id'], name=op.f('fk__file_system__parentId__relations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__file_system'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_system')
    op.drop_table('relations')
    types.drop(op.get_bind())
    # ### end Alembic commands ###
